/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.0.35
 * Generated at: 2016-10-25 06:59:33 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class cart_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("/WEB-INF/lib/jstl-1.2.jar", Long.valueOf(1476422983092L));
    _jspx_dependants.put("jar:file:/G:/DTProject/DT/.metadata/.plugins/org.eclipse.wst.server.core/tmp1/wtpwebapps/yash_webapp_01/WEB-INF/lib/jstl-1.2.jar!/META-INF/c.tld", Long.valueOf(1153365282000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.release();
    _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

final java.lang.String _jspx_method = request.getMethod();
if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
return;
}

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=ISO-8859-1");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=ISO-8859-1\">\r\n");
      out.write("<link rel=\"stylesheet\"\r\n");
      out.write("\thref=\"https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css\">\r\n");
      out.write("<link rel=\"stylesheet\"\r\n");
      out.write("\thref=\"https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"./resources/my.css\">\r\n");
      out.write("<link href=\"/css/bootstrap.min.css\" rel=\"stylesheet\">\r\n");
      out.write("<link href=\"/css/styles.css\" rel=\"stylesheet\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"css/demo.css\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"css/footer-basic-centered.css\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"./resources/crunchify.css\">\r\n");
      out.write("<link rel=\"stylesheet\"\r\n");
      out.write("\thref=\"http://maxcdn.bootstrapcdn.com/bootstrap/3.3.4/css/bootstrap.min.css\">\r\n");
      out.write("<link\r\n");
      out.write("\thref='https://fonts.googleapis.com/css?family=Open+Sans+Condensed:300,700'\r\n");
      out.write("\trel='stylesheet'>\r\n");
      out.write("<link\r\n");
      out.write("\thref=\"https://maxcdn.bootstrapcdn.com/font-awesome/4.6.3/css/font-awesome.min.css\"\r\n");
      out.write("\trel=\"stylesheet\">\r\n");
      out.write("<link rel=\"stylesheet\"\r\n");
      out.write("\thref=\"http://maxcdn.bootstrapcdn.com/bootstrap/3.3.4/css/bootstrap.min.css\">\r\n");
      out.write("<link\r\n");
      out.write("\thref='https://fonts.googleapis.com/css?family=Open+Sans+Condensed:300,700'\r\n");
      out.write("\trel='stylesheet'>\r\n");
      out.write("<link\r\n");
      out.write("\thref=\"https://maxcdn.bootstrapcdn.com/font-awesome/4.6.3/css/font-awesome.min.css\"\r\n");
      out.write("\trel=\"stylesheet\">\r\n");
      out.write("<script\r\n");
      out.write("\tsrc=\"https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js\"></script>\r\n");
      out.write("<script\r\n");
      out.write("\tsrc=\"https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js\"></script>\r\n");
      out.write("\r\n");
      out.write("<link rel=\"stylesheet\"\r\n");
      out.write("\thref=\"http://maxcdn.bootstrapcdn.com/bootstrap/3.3.4/css/bootstrap.min.css\">\r\n");
      out.write("<link\r\n");
      out.write("\thref='https://fonts.googleapis.com/css?family=Open+Sans+Condensed:300,700'\r\n");
      out.write("\trel='stylesheet'>\r\n");
      out.write("<link\r\n");
      out.write("\thref=\"https://maxcdn.bootstrapcdn.com/font-awesome/4.6.3/css/font-awesome.min.css\"\r\n");
      out.write("\trel=\"stylesheet\">\r\n");
      out.write("<!--[if lt IE 9]>\r\n");
      out.write("<script src=https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js></script>\r\n");
      out.write("<script src=https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js></script>\r\n");
      out.write("<![endif]-->\r\n");
      out.write("<script>\r\n");
      out.write("\t!function(e, a, t, n, c, o, s) {\r\n");
      out.write("\t\te.GoogleAnalyticsObject = c, e[c] = e[c] || function() {\r\n");
      out.write("\t\t\t(e[c].q = e[c].q || []).push(arguments)\r\n");
      out.write("\t\t}, e[c].l = 1 * new Date, o = a.createElement(t), s = a\r\n");
      out.write("\t\t\t\t.getElementsByTagName(t)[0], o.async = 1, o.src = n,\r\n");
      out.write("\t\t\t\ts.parentNode.insertBefore(o, s)\r\n");
      out.write("\t}(window, document, \"script\", \"//www.google-analytics.com/analytics.js\",\r\n");
      out.write("\t\t\t\"ga\"), ga(\"create\", \"UA-47210639-2\", \"auto\"),\r\n");
      out.write("\t\t\tga(\"send\", \"pageview\")\r\n");
      out.write("</script>\r\n");
      out.write("<script type=application/ld+json>{ \"@context\": \"http://schema.org/\",\"@type\": \"Review\",\"itemReviewed\": {\"@type\": \"Thing\",\"name\": \"Article\"},\"author\": {\"@type\": \"Person\",\"name\": \"Md Ashraf Malik\"}, \"reviewRating\": {\"@type\": \"Rating\",\"ratingValue\": \"5\",\"bestRating\": \"5\"}, \"publisher\": { \"@type\": \"Organization\", \"name\": \"Web Developer Bareilly\" } }</script>\r\n");
      out.write("<style>\r\n");
      out.write("\r\n");
      out.write("/* header */\r\n");
      out.write("html, body {\r\n");
      out.write("\theight: 100%;\r\n");
      out.write("\twidth: 100%\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("h1, h2, h3 {\r\n");
      out.write("\tfont-weight: 700\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("header {\r\n");
      out.write("\tposition: relative;\r\n");
      out.write("\twidth: 100%;\r\n");
      out.write("\tbackground-size: cover;\r\n");
      out.write("\tbackground-position: center;\r\n");
      out.write("\tbackground-image: url(images/header.jpg);\r\n");
      out.write("\ttext-align: center\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("header .wel {\r\n");
      out.write("\tposition: relative;\r\n");
      out.write("\ttext-align: center;\r\n");
      out.write("\tpadding: 100px 15px 100px;\r\n");
      out.write("\twidth: 100%;\r\n");
      out.write("\tcolor: #eee\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".wel h1 {\r\n");
      out.write("\tfont-weight: 700;\r\n");
      out.write("\tcolor: #fff\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".brk {\r\n");
      out.write("\theight: 4px;\r\n");
      out.write("\tborder-radius: 4px;\r\n");
      out.write("\tbackground: #d9534f;\r\n");
      out.write("\tmargin: 25px auto;\r\n");
      out.write("\tdisplay: block;\r\n");
      out.write("\twidth: 60px\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".abs-back {\r\n");
      out.write("\tbackground: rgba(29, 21, 24, 0.4);\r\n");
      out.write("\tposition: absolute;\r\n");
      out.write("\theight: 100%;\r\n");
      out.write("\twidth: 100%;\r\n");
      out.write("\tleft: 0;\r\n");
      out.write("\ttop: 0\r\n");
      out.write("}\r\n");
      out.write("/* who we */\r\n");
      out.write(".who-we {\r\n");
      out.write("\tmargin-top: 50px;\r\n");
      out.write("\tmargin-bottom: 50px\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".who-we h2 {\r\n");
      out.write("\tcolor: #d9534f;\r\n");
      out.write("}\r\n");
      out.write("/* cards*/\r\n");
      out.write(".cards-row {\r\n");
      out.write("\tpadding-top: 70px;\r\n");
      out.write("\tpadding-bottom: 50px;\r\n");
      out.write("\tbackground: #eee\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".thumbnail {\r\n");
      out.write("\tpadding: 0;\r\n");
      out.write("\tborder-radius: 0;\r\n");
      out.write("\tborder: none;\r\n");
      out.write("\tbox-shadow: 0 2px 2px 0 rgba(0, 0, 0, .14), 0 3px 1px -2px\r\n");
      out.write("\t\trgba(0, 0, 0, .2), 0 1px 5px 0 rgba(0, 0, 0, .12)\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".thumbnail>img {\r\n");
      out.write("\twidth: 100%;\r\n");
      out.write("\tdisplay: block\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".thumbnail h3 {\r\n");
      out.write("\tfont-size: 26px;\r\n");
      out.write("\tcolor: #336\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".thumbnail h3, .card-description {\r\n");
      out.write("\tmargin: 0;\r\n");
      out.write("\tpadding: 8px 0;\r\n");
      out.write("\tborder-bottom: solid 1px #eee;\r\n");
      out.write("\ttext-align: center\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".thumbnail p {\r\n");
      out.write("\tpadding-top: 8px;\r\n");
      out.write("\tfont-size: 20px\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".thumbnail .btn {\r\n");
      out.write("\tborder-radius: 0;\r\n");
      out.write("\tbox-shadow: 0 2px 5px 0 rgba(0, 0, 0, .16), 0 2px 10px 0\r\n");
      out.write("\t\trgba(0, 0, 0, .12);\r\n");
      out.write("\tfont-size: 20px\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".team-pic {\r\n");
      out.write("\theight: 150px !important;\r\n");
      out.write("\twidth: 150px !important;\r\n");
      out.write("\tborder-radius: 50%;\r\n");
      out.write("\tmargin-top: -75px;\r\n");
      out.write("\tbox-shadow: 0 2px 5px 0 rgba(0, 0, 0, .4), 0 2px 10px 0\r\n");
      out.write("\t\trgba(0, 0, 0, .5);\r\n");
      out.write("\ttransition: all .2s ease-out\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".thumbnail:hover .team-pic {\r\n");
      out.write("\theight: 200px !important;\r\n");
      out.write("\twidth: 200px !important;\r\n");
      out.write("\tmargin-top: -100px\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".thumbnail p.social {\r\n");
      out.write("\tpadding-top: 15px;\r\n");
      out.write("\ttext-align: center\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".social a {\r\n");
      out.write("\tcolor: #FFF;\r\n");
      out.write("\tfont-size: 18px !important\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".social i.fa {\r\n");
      out.write("\theight: 36px;\r\n");
      out.write("\twidth: 36px;\r\n");
      out.write("\ttext-align: center;\r\n");
      out.write("\tline-height: 36px;\r\n");
      out.write("\tbackground: #069;\r\n");
      out.write("\tborder-radius: 50%\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".social i.fa.fa-facebook {\r\n");
      out.write("\tbackground: #43609C\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".social i.fa.fa-twitter {\r\n");
      out.write("\tbackground: #2CA8D2\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".social i.fa.fa-linkedin {\r\n");
      out.write("\tbackground: #428099\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".social i.fa.fa-google-plus {\r\n");
      out.write("\tbackground: #ce4d39\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("/* media */\r\n");
      out.write("@media ( min-width :768px) {\r\n");
      out.write("</style>\r\n");
      out.write("<!-- Finish adding tags -->\r\n");
      out.write("\r\n");
      out.write("<title>Happy World</title>\r\n");
      out.write("<style type=\"text/css\">\r\n");
      out.write("#footer {\r\n");
      out.write("\tbackground: #336;\r\n");
      out.write("\tpadding-top: 30px;\r\n");
      out.write("\tpadding-bottom: 30px;\r\n");
      out.write("\ttext-align: center;\r\n");
      out.write("\tborder-top: solid 4px #303\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#footer p {\r\n");
      out.write("\tpadding: 10px;\r\n");
      out.write("\tcolor: #fff\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".dont-remove {\r\n");
      out.write("\tcolor: #fff !important;\r\n");
      out.write("\ttext-decoration: none !important;\r\n");
      out.write("\tfont-weight: 700\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".rights {\r\n");
      out.write("\tdisplay: inline-block;\r\n");
      out.write("\tborder-top: solid 1px rgba(103, 58, 183, 0.3)\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("body {\r\n");
      out.write("\tbackground-image: url('http://crunchify.com/bg.png');\r\n");
      out.write("}\r\n");
      out.write("</style>\r\n");
      out.write("<title>Cart</title>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\t");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "header.jsp", out, false);
      out.write("\r\n");
      out.write("\t<div class=\"container\">&nbsp;</div>\r\n");
      out.write("\t<div class=\"container\">&nbsp;</div>\r\n");
      out.write("\t<div align=\"center\">\r\n");
      out.write("\t\t<h1>VanuShopping.com Cart Page</h1>\r\n");
      out.write("\t\t<table border=\"2\">\r\n");
      out.write("\t\t\t<tr>\r\n");
      out.write("\t\t\t\t<th>Options</th>\r\n");
      out.write("\t\t\t\t<th>Id</th>\r\n");
      out.write("\t\t\t\t<th>Photo</th>\r\n");
      out.write("\t\t\t\t<th>Name</th>\r\n");
      out.write("\t\t\t\t<th>Price</th>\r\n");
      out.write("\t\t\t\t<th>Quantity</th>\r\n");
      out.write("\t\t\t\t<th>Sub Total</th>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\t\t</tr>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\t\t");
      if (_jspx_meth_c_005fset_005f0(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("\t\t\t");
      if (_jspx_meth_c_005fforEach_005f0(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\t\t<tr>\r\n");
      out.write("\t\t\t\t<td colspan=\"6\" align=\"right\">Sum</td>\r\n");
      out.write("\t\t\t\t<td>");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${s}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</td>\r\n");
      out.write("\r\n");
      out.write("\t\t\t</tr>\r\n");
      out.write("\r\n");
      out.write("\t\t</table>\r\n");
      out.write("\t\t<button><a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/shipping\">Proceed to pay</a></button>\r\n");
      out.write("\t\t<br>\r\n");
      out.write("\r\n");
      out.write("\t</div>\r\n");
      out.write("\t\r\n");
      out.write("\t</div>\r\n");
      out.write("<div class=\"container\">\r\n");
      out.write("    &nbsp;\r\n");
      out.write("  </div>\r\n");
      out.write("   <div class=\"container\">\r\n");
      out.write("    &nbsp;\r\n");
      out.write("  </div>\r\n");
      out.write("   <div class=\"container\">\r\n");
      out.write("    &nbsp;\r\n");
      out.write("  </div>\r\n");
      out.write("   <div class=\"container\">\r\n");
      out.write("    &nbsp;\r\n");
      out.write("  </div>\r\n");
      out.write("   <div class=\"container\">\r\n");
      out.write("    &nbsp;\r\n");
      out.write("  </div>\r\n");
      out.write("   <div class=\"container\">\r\n");
      out.write("    &nbsp;\r\n");
      out.write("  </div>\r\n");
      out.write("   <div class=\"container\">\r\n");
      out.write("    &nbsp;\r\n");
      out.write("  </div>\r\n");
      out.write("   <div class=\"container\">\r\n");
      out.write("    &nbsp;\r\n");
      out.write("  </div>\r\n");
      out.write("   <div class=\"container\">\r\n");
      out.write("    &nbsp;\r\n");
      out.write("  </div>\r\n");
      out.write("   <div class=\"container\">\r\n");
      out.write("    &nbsp;\r\n");
      out.write("  </div>\r\n");
      out.write("   <div class=\"container\">\r\n");
      out.write("    &nbsp;\r\n");
      out.write("  </div>\r\n");
      out.write("    &nbsp;\r\n");
      out.write("  </div>\r\n");
      out.write("   <div class=\"container\">\r\n");
      out.write("    &nbsp;\r\n");
      out.write("  </div>\r\n");
      out.write("   <div class=\"container\">\r\n");
      out.write("    &nbsp;\r\n");
      out.write("  </div>\r\n");
      out.write("   <div class=\"container\">\r\n");
      out.write("    &nbsp;\r\n");
      out.write("  </div>\r\n");
      out.write("    &nbsp;\r\n");
      out.write("  </div>\r\n");
      out.write("\r\n");
      out.write("\t");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "footer.jsp", out, false);
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_c_005fset_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:set
    org.apache.taglibs.standard.tag.rt.core.SetTag _jspx_th_c_005fset_005f0 = (org.apache.taglibs.standard.tag.rt.core.SetTag) _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.SetTag.class);
    _jspx_th_c_005fset_005f0.setPageContext(_jspx_page_context);
    _jspx_th_c_005fset_005f0.setParent(null);
    // /WEB-INF/views/cart.jsp(277,3) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_c_005fset_005f0.setVar("s");
    // /WEB-INF/views/cart.jsp(277,3) name = value type = javax.el.ValueExpression reqTime = true required = false fragment = false deferredValue = true expectedTypeName = java.lang.Object deferredMethod = false methodSignature = null
    _jspx_th_c_005fset_005f0.setValue(new org.apache.jasper.el.JspValueExpression("/WEB-INF/views/cart.jsp(277,3) '0'",_jsp_getExpressionFactory().createValueExpression("0",java.lang.Object.class)).getValue(_jspx_page_context.getELContext()));
    int _jspx_eval_c_005fset_005f0 = _jspx_th_c_005fset_005f0.doStartTag();
    if (_jspx_th_c_005fset_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.reuse(_jspx_th_c_005fset_005f0);
      return true;
    }
    _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.reuse(_jspx_th_c_005fset_005f0);
    return false;
  }

  private boolean _jspx_meth_c_005fforEach_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:forEach
    org.apache.taglibs.standard.tag.rt.core.ForEachTag _jspx_th_c_005fforEach_005f0 = (org.apache.taglibs.standard.tag.rt.core.ForEachTag) _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.get(org.apache.taglibs.standard.tag.rt.core.ForEachTag.class);
    _jspx_th_c_005fforEach_005f0.setPageContext(_jspx_page_context);
    _jspx_th_c_005fforEach_005f0.setParent(null);
    // /WEB-INF/views/cart.jsp(278,3) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_c_005fforEach_005f0.setVar("pr");
    // /WEB-INF/views/cart.jsp(278,3) name = items type = javax.el.ValueExpression reqTime = true required = false fragment = false deferredValue = true expectedTypeName = java.lang.Object deferredMethod = false methodSignature = null
    _jspx_th_c_005fforEach_005f0.setItems(new org.apache.jasper.el.JspValueExpression("/WEB-INF/views/cart.jsp(278,3) '${sessionScope.cart}'",_jsp_getExpressionFactory().createValueExpression(_jspx_page_context.getELContext(),"${sessionScope.cart}",java.lang.Object.class)).getValue(_jspx_page_context.getELContext()));
    int[] _jspx_push_body_count_c_005fforEach_005f0 = new int[] { 0 };
    try {
      int _jspx_eval_c_005fforEach_005f0 = _jspx_th_c_005fforEach_005f0.doStartTag();
      if (_jspx_eval_c_005fforEach_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("\t\t\t\t");
          if (_jspx_meth_c_005fset_005f1(_jspx_th_c_005fforEach_005f0, _jspx_page_context, _jspx_push_body_count_c_005fforEach_005f0))
            return true;
          out.write("\r\n");
          out.write("\t\t\t\t<tr>\r\n");
          out.write("\t\t\t\t\t<td><a\r\n");
          out.write("\t\t\t\t\t\thref=\"");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("/shoppingcart/delete/");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pr.product.id }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write(".html\">Remove</a></td>\r\n");
          out.write("\t\t\t\t\t<td>");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pr.product.id }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("</td>\r\n");
          out.write("\r\n");
          out.write("\t\t\t\t\t<td><img alt=\"\"\r\n");
          out.write("\t\t\t\t\t\tsrc=\"");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("/images/");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pr.product.photo}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("\"\r\n");
          out.write("\t\t\t\t\t\theight=\"100px\" width=\"100px\"></td>\r\n");
          out.write("\r\n");
          out.write("\t\t\t\t\t<td>");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pr.product.name }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("</td>\r\n");
          out.write("\t\t\t\t\t<td>");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pr.product.price }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("</td>\r\n");
          out.write("\t\t\t\t\t<td>");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pr.product.quantity }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("</td>\r\n");
          out.write("\t\t\t\t\t<td>");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pr.product.price * pr.product.quantity}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("</td>\r\n");
          out.write("\t\t\t\t</tr>\r\n");
          out.write("\r\n");
          out.write("\r\n");
          out.write("\r\n");
          out.write("\r\n");
          out.write("\r\n");
          out.write("\r\n");
          out.write("\t\t\t");
          int evalDoAfterBody = _jspx_th_c_005fforEach_005f0.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fforEach_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
    } catch (java.lang.Throwable _jspx_exception) {
      while (_jspx_push_body_count_c_005fforEach_005f0[0]-- > 0)
        out = _jspx_page_context.popBody();
      _jspx_th_c_005fforEach_005f0.doCatch(_jspx_exception);
    } finally {
      _jspx_th_c_005fforEach_005f0.doFinally();
      _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.reuse(_jspx_th_c_005fforEach_005f0);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fset_005f1(javax.servlet.jsp.tagext.JspTag _jspx_th_c_005fforEach_005f0, javax.servlet.jsp.PageContext _jspx_page_context, int[] _jspx_push_body_count_c_005fforEach_005f0)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:set
    org.apache.taglibs.standard.tag.rt.core.SetTag _jspx_th_c_005fset_005f1 = (org.apache.taglibs.standard.tag.rt.core.SetTag) _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.SetTag.class);
    _jspx_th_c_005fset_005f1.setPageContext(_jspx_page_context);
    _jspx_th_c_005fset_005f1.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005fforEach_005f0);
    // /WEB-INF/views/cart.jsp(279,4) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_c_005fset_005f1.setVar("s");
    // /WEB-INF/views/cart.jsp(279,4) name = value type = javax.el.ValueExpression reqTime = true required = false fragment = false deferredValue = true expectedTypeName = java.lang.Object deferredMethod = false methodSignature = null
    _jspx_th_c_005fset_005f1.setValue(new org.apache.jasper.el.JspValueExpression("/WEB-INF/views/cart.jsp(279,4) '${s+ pr.product.price * pr.product.quantity}'",_jsp_getExpressionFactory().createValueExpression(_jspx_page_context.getELContext(),"${s+ pr.product.price * pr.product.quantity}",java.lang.Object.class)).getValue(_jspx_page_context.getELContext()));
    int _jspx_eval_c_005fset_005f1 = _jspx_th_c_005fset_005f1.doStartTag();
    if (_jspx_th_c_005fset_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.reuse(_jspx_th_c_005fset_005f1);
      return true;
    }
    _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.reuse(_jspx_th_c_005fset_005f1);
    return false;
  }
}
