/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.0.35
 * Generated at: 2016-10-26 06:53:48 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class viewall_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("/WEB-INF/lib/jstl-1.2.jar", Long.valueOf(1476422983092L));
    _jspx_dependants.put("jar:file:/G:/DTProject/DT/.metadata/.plugins/org.eclipse.wst.server.core/tmp1/wtpwebapps/yash_webapp_01/WEB-INF/lib/jstl-1.2.jar!/META-INF/c.tld", Long.valueOf(1153365282000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

final java.lang.String _jspx_method = request.getMethod();
if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
return;
}

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html >\r\n");
      out.write("  <head>\r\n");
      out.write("  \r\n");
      out.write("    <script src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${req}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/js/angular.js\"></script>\r\n");
      out.write("     <script src=\"http://code.angularjs.org/snapshot/angular.js\"></script>\r\n");
      out.write("    <meta charset=\"UTF-8\"> \r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("      <title>VanuShopping-Search your product</title>\r\n");
      out.write("    \r\n");
      out.write("    <link rel=\"stylesheet\" href=\"https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"./resources/my.css\">\r\n");
      out.write("<link href=\"/css/bootstrap.min.css\" rel=\"stylesheet\">\r\n");
      out.write("<link href=\"/css/styles.css\" rel=\"stylesheet\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"http://maxcdn.bootstrapcdn.com/bootstrap/3.3.4/css/bootstrap.min.css\">\r\n");
      out.write("<link href='https://fonts.googleapis.com/css?family=Open+Sans+Condensed:300,700' rel='stylesheet'>\r\n");
      out.write("<link href=\"https://maxcdn.bootstrapcdn.com/font-awesome/4.6.3/css/font-awesome.min.css\" rel=\"stylesheet\">\r\n");
      out.write(" <script src=\"https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js\"></script>\r\n");
      out.write("  <script src=\"https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js\"></script>\r\n");
      out.write("  \r\n");
      out.write("    \r\n");
      out.write("<link rel='stylesheet prefetch' href='//maxcdn.bootstrapcdn.com/font-awesome/4.2.0/css/font-awesome.min.css'>\r\n");
      out.write("<link rel=\"stylesheet\" href=\"http://maxcdn.bootstrapcdn.com/bootstrap/3.3.4/css/bootstrap.min.css\">\r\n");
      out.write("<link href='https://fonts.googleapis.com/css?family=Open+Sans+Condensed:300,700' rel='stylesheet'>\r\n");
      out.write("<link href=\"https://maxcdn.bootstrapcdn.com/font-awesome/4.6.3/css/font-awesome.min.css\" rel=\"stylesheet\">\r\n");
      out.write("<!--[if lt IE 9]>\r\n");
      out.write("<script src=https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js></script>\r\n");
      out.write("<script src=https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js></script>\r\n");
      out.write("<![endif]-->\r\n");
      out.write("<script>!function(e,a,t,n,c,o,s){e.GoogleAnalyticsObject=c,e[c]=e[c]||function(){(e[c].q=e[c].q||[]).push(arguments)},e[c].l=1*new Date,o=a.createElement(t),s=a.getElementsByTagName(t)[0],o.async=1,o.src=n,s.parentNode.insertBefore(o,s)}(window,document,\"script\",\"//www.google-analytics.com/analytics.js\",\"ga\"),ga(\"create\",\"UA-47210639-2\",\"auto\"),ga(\"send\",\"pageview\")</script><script type=application/ld+json>{ \"@context\": \"http://schema.org/\",\"@type\": \"Review\",\"itemReviewed\": {\"@type\": \"Thing\",\"name\": \"Article\"},\"author\": {\"@type\": \"Person\",\"name\": \"Md Ashraf Malik\"}, \"reviewRating\": {\"@type\": \"Rating\",\"ratingValue\": \"5\",\"bestRating\": \"5\"}, \"publisher\": { \"@type\": \"Organization\", \"name\": \"Web Developer Bareilly\" } }</script>\r\n");
      out.write("<style>\r\n");
      out.write("\r\n");
      out.write("/* header */\r\n");
      out.write("html,body{height:100%; width:100%}\r\n");
      out.write("h1,h2,h3{font-weight:700}\r\n");
      out.write("header{position:relative; width:100%; background-size:cover; background-position:center; background-image:url(images/header.jpg); text-align:center}\r\n");
      out.write("header .wel{position: relative;text-align: center;padding: 100px 15px 100px;width: 100%; color:#eee}\r\n");
      out.write(".wel h1{font-weight:700; color:#fff}.brk{height:4px; border-radius:4px; background:#d9534f; margin:25px auto; display:block; width:60px}\r\n");
      out.write(".abs-back{background:rgba(29, 21, 24, 0.4); position:absolute; height:100%; width:100%; left:0; top:0}\r\n");
      out.write("/* who we */\r\n");
      out.write(".who-we{margin-top:50px; margin-bottom:50px}\r\n");
      out.write(".who-we h2{color:#d9534f;}\r\n");
      out.write("/* cards*/\r\n");
      out.write(".cards-row{padding-top:70px; padding-bottom:50px; background:#eee}\r\n");
      out.write(".thumbnail{padding:0; border-radius:0; border:none; box-shadow:0 2px 2px 0 rgba(0,0,0,.14),0 3px 1px -2px rgba(0,0,0,.2),0 1px 5px 0 rgba(0,0,0,.12)}\r\n");
      out.write(".thumbnail>img{width:100%; display:block}\r\n");
      out.write(".thumbnail h3{font-size:26px; color:#336}\r\n");
      out.write(".thumbnail h3,.card-description{margin:0; padding:8px 0; border-bottom:solid 1px #eee; text-align:center}\r\n");
      out.write(".thumbnail p{padding-top:8px; font-size:20px}\r\n");
      out.write(".thumbnail .btn{border-radius:0; box-shadow:0 2px 5px 0 rgba(0,0,0,.16),0 2px 10px 0 rgba(0,0,0,.12); font-size:20px}\r\n");
      out.write(".team-pic{height:150px !important; width:150px !important; border-radius:50%; margin-top:-75px; box-shadow:0 2px 5px 0 rgba(0,0,0,.4),0 2px 10px 0 rgba(0,0,0,.5); transition:all .2s ease-out}\r\n");
      out.write(".thumbnail:hover .team-pic{height:200px !important; width:200px !important; margin-top:-100px}\r\n");
      out.write(".thumbnail p.social{padding-top:15px; text-align:center}\r\n");
      out.write(".social a{color:#FFF; font-size:18px !important}\r\n");
      out.write(".social i.fa{height:36px; width:36px; text-align:center; line-height:36px; background:#069; border-radius:50%}\r\n");
      out.write(".social i.fa.fa-facebook{background:#43609C}\r\n");
      out.write(".social i.fa.fa-twitter{background:#2CA8D2}\r\n");
      out.write(".social i.fa.fa-linkedin{background:#428099}\r\n");
      out.write(".social i.fa.fa-google-plus{background:#ce4d39}\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("/* media */\r\n");
      out.write("@media (min-width:768px) { \r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</style>\r\n");
      out.write("        <style>\r\n");
      out.write("      /*\r\n");
      out.write("  were using Bootstrap and Font Awesome\r\n");
      out.write("  http://bootstrapcdn.com\r\n");
      out.write("  \r\n");
      out.write("*/\r\n");
      out.write(".spacer { margin:0; padding:0; height:50px; }\r\n");
      out.write(" .popup-trigger { display: block; margin: 0 auto; padding: 20px; max-width: 260px; background: #4EBD79; color: #fff;\r\n");
      out.write("                 font-size: 18px; font-weight: 700; text-align: center; text-transform: uppercase; line-height: 24px; cursor: pointer; }\r\n");
      out.write("        .popup {display: none; position: absolute; top: 100px; left: 50%; width: 700px; margin-left: -350px; padding: 50px 30px;\r\n");
      out.write("            background: #fff; color: #333; font-size: 19px; line-height: 30px; border: 10px solid #150E2D; z-index: 9999;}\r\n");
      out.write("        .popup-mobile {position: relative; top: 0; left: 0; margin: 30px 0 0; width: 100%;}   \r\n");
      out.write("          .popup-btn-close {position: absolute; top: 8px; right: 14px; color: #4EBD79; font-size: 14px; font-weight: bold; text-transform: uppercase; cursor: pointer;} \r\n");
      out.write("\r\n");
      out.write("body { padding-top:50px; }\r\n");
      out.write("#footer{background:#336; padding-top:30px; padding-bottom:30px; text-align:center; border-top:solid 4px #303}\r\n");
      out.write("#footer p{padding:10px; color:#fff}\r\n");
      out.write(".dont-remove{color:#fff !important; text-decoration:none !important; font-weight:700}\r\n");
      out.write(".rights{display:inline-block; border-top:solid 1px rgba(103, 58, 183, 0.3)}\r\n");
      out.write("#footer{background:#336; padding-top:30px; padding-bottom:30px; text-align:center; border-top:solid 4px #303}\r\n");
      out.write("#footer p{padding:10px; color:#fff}\r\n");
      out.write(".dont-remove{color:#fff !important; text-decoration:none !important; font-weight:700}\r\n");
      out.write(".rights{display:inline-block; border-top:solid 1px rgba(103, 58, 183, 0.3)}\r\n");
      out.write("    </style>\r\n");
      out.write("\r\n");
      out.write("    <script>\r\n");
      out.write("  window.console = window.console || function(t) {};\r\n");
      out.write("</script>\r\n");
      out.write("\r\n");
      out.write("    \r\n");
      out.write("    \r\n");
      out.write("    <script>\r\n");
      out.write("  if (document.location.search.match(/type=embed/gi)) {\r\n");
      out.write("    window.parent.postMessage(\"resize\", \"*\");\r\n");
      out.write("  }\r\n");
      out.write("</script>\r\n");
      out.write("  \r\n");
      out.write("  \r\n");
      out.write("\r\n");
      out.write("      <style>\r\n");
      out.write("      /*\r\n");
      out.write("  were using Bootstrap and Font Awesome\r\n");
      out.write("  http://bootstrapcdn.com\r\n");
      out.write("*/\r\n");
      out.write("\r\n");
      out.write("body { padding-top:50px; }\r\n");
      out.write("    </style>\r\n");
      out.write("\r\n");
      out.write("    <script>\r\n");
      out.write("  window.console = window.console || function(t) {};\r\n");
      out.write("</script>\r\n");
      out.write("\r\n");
      out.write("    \r\n");
      out.write("    \r\n");
      out.write("    <script>\r\n");
      out.write("  if (document.location.search.match(/type=embed/gi)) {\r\n");
      out.write("    window.parent.postMessage(\"resize\", \"*\");\r\n");
      out.write("  }\r\n");
      out.write("</script>\r\n");
      out.write("<script>\r\n");
      out.write("var app = angular.module('myApp', []);\r\n");
      out.write("app.controller('myCtrl', function($scope, $http) {\r\n");
      out.write(" $http.get(\"/pro/view\")\r\n");
      out.write("  .then(function(response) {\r\n");
      out.write("      $scope.names= response.data;\r\n");
      out.write("  });\r\n");
      out.write("});\r\n");
      out.write("</script>\r\n");
      out.write("\r\n");
      out.write("  </head>\r\n");
      out.write("\r\n");
      out.write("  <body translate=\"no\" >\r\n");
      out.write("  ");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "header.jsp", out, false);
      out.write("\r\n");
      out.write("  <h3 align=\"center\">Search for the products you are looking for</h3>\r\n");
      out.write("  <div class=\"container\">\r\n");
      out.write("    &nbsp;\r\n");
      out.write("  </div>\r\n");
      out.write("  \r\n");
      out.write("\r\n");
      if (_jspx_meth_c_005fset_005f0(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("<spring:url value=\"/resources/images/product\" var=\"productImages\" />\r\n");
      out.write("\r\n");
      out.write("<script src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${req}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/js/angular.js\"></script>\r\n");
      out.write("\r\n");
      out.write("<div ng-app=\"myApp\" ng-controller=\"myCtrl\" ng-init=\"test='");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pid}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("'\">\r\n");
      out.write("\r\n");
      out.write("\t<p>\r\n");
      out.write("\t\tSearch:<input type=\"text\" ng-model=\"test\" class=\"form-control\" id=\"usr\" />\r\n");
      out.write("\t</p>\r\n");
      out.write("\r\n");
      out.write("\t<table border=\"1\" width=\"50%\"\r\n");
      out.write("\t\tclass=\"table table-hover table-responsive\">\r\n");
      out.write("\t\t<tr>\r\n");
      out.write("\t\t\t<th ng-click=\"orderByMe('pid')\">Product ID</th>\r\n");
      out.write("\t\t\t<th ng-click=\"orderByMe('pbrand')\">Product Brand</th>\r\n");
      out.write("\t\t\t<th ng-click=\"orderByMe('pmodel')\">Product Model</th>\r\n");
      out.write("\t\t\t<th ng-click=\"orderByMe('pos')\">Product Os</th>\r\n");
      out.write("\t\t\t<th ng-click=\"orderByMe('pversion')\">Product Version</th>\r\n");
      out.write("\t\t\t<!-- <th ng-click=\"orderByMe('purl')\">Product Image</th>-->\r\n");
      out.write("\t\t\t<th ng-click=\"orderByMe('pprice')\">Product Price</th>\r\n");
      out.write("\t\t\t<th ng-click=\"\">Image</th>\r\n");
      out.write("\t\t\t<th ng-click=\"\"></th>\r\n");
      out.write("\t\t</tr>\r\n");
      out.write("\r\n");
      out.write("\t\t<tr ng-repeat=\"x in names | orderBy:myOrderBy | filter:test\">\r\n");
      out.write("\t\t\t<td>{{x.pid}}</td>\r\n");
      out.write("\t\t\t<td>{{x.pbrand}}</td>\r\n");
      out.write("\t\t\t<td>{{x.pmodel}}</td>\r\n");
      out.write("\t\t\t<td>{{x.pos}}</td>\r\n");
      out.write("\t\t\t<td>{{x.pversion}}</td>\r\n");
      out.write("\t\t\t<td>{{x.pprice}}</td>\r\n");
      out.write("\t\t\t<td><img ng-src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${productImages}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/{{x.pid}}.jpg\" width=\"50\"\r\n");
      out.write("\t\t\t\t\theight=\"50\"></td>\r\n");
      out.write("\t\t\t<td><a ng-href=\"/yash_webapp_01/pro/view/{{x.pid}}\"\r\n");
      out.write("\t\t\t\tclass=\"btn btn-info\" role=\"button\" data-toggle=\"modal\" data-target=\"#myModal\">View</a></td>\r\n");
      out.write("\t\t</tr>\r\n");
      out.write("\t</table>\r\n");
      out.write("</div>\r\n");
      out.write("<script>\r\n");
      out.write("\tvar app = angular.module('myApp', []);\r\n");
      out.write("\tapp.controller('myCtrl', function($scope, $http) {\r\n");
      out.write("\t\t$http.get(\"/yash_webapp_01/viewdetails\").then(function(response) {\r\n");
      out.write("\t\t\t$scope.names = response.data;\r\n");
      out.write("\t\t});\r\n");
      out.write("\t\t$scope.orderByMe = function(x) {\r\n");
      out.write("\t\t\t$scope.myOrderBy = x;\r\n");
      out.write("\t\t}\r\n");
      out.write("\t});\r\n");
      out.write("</script>\r\n");
      out.write("\r\n");
      out.write("<!-- Modal -->\r\n");
      out.write("<div class=\"modal fade\" id=\"myModal\" tabindex=\"-1\" role=\"dialog\" aria-labelledby=\"myModalLabel\" aria-hidden=\"true\">\r\n");
      out.write("    <div class=\"modal-dialog\">\r\n");
      out.write("        <div class=\"modal-content\">\r\n");
      out.write("            <div class=\"modal-header\">\r\n");
      out.write("                <button type=\"button\" class=\"close\" data-dismiss=\"modal\" aria-hidden=\"true\">&times;</button>\r\n");
      out.write("                <h4 class=\"modal-title\" id=\"myModalLabel\">Modal title</h4>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"modal-body\">\r\n");
      out.write("             \r\n");
      out.write("      <div class=\"panel pannel-default\">\r\n");
      out.write("\t<div class=\"panel-header\" align=\"center\">Product Form</div>\r\n");
      out.write("\t<div class=\"panel-body\">\r\n");
      out.write(" \r\n");
      out.write("\t\t<form:form action=\"\" method=\"post\" modelAttribute=\"product\" enctype=\"multipart/form-data\">\r\n");
      out.write("\t\t\t<table border=\"1\" width=\"600\" align=\"center\">\r\n");
      out.write("\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t<td></td>\r\n");
      out.write("\t\t\t\t\t<td><form:hidden path=\"pid\" /></td>\r\n");
      out.write("\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t<td>Product Category</td>\r\n");
      out.write("\t\t\t\t\t<td><form:input path=\"pcat\" cssClass=\"form-control\" disabled=\"true\"/><error path=\"pcat\" cssclass=\"error\" />\r\n");
      out.write("\t\t\t\t\t<span><form:errors  path=\"pcat\" cssclass=\"error\" disabled=\"true\" /> </span></td>\r\n");
      out.write("\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t<td>Product Brand</td>\r\n");
      out.write("\t\t\t\t\t<td><form:input path=\"pbrand\" cssClass=\"form-control\" disabled=\"true\"/></td>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t<td>Product Model</td>\r\n");
      out.write("\t\t\t\t\t<td><form:input path=\"pmodel\" cssClass=\"form-control\" disabled=\"true\"/></td>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t<td>Product Os</td>\r\n");
      out.write("\t\t\t\t\t<td><form:input path=\"pos\" cssClass=\"form-control\" disabled=\"true\"/></td>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t<td>Product Version>\r\n");
      out.write("\t\t\t\t\t<td><form:input path=\"pversion\" cssClass=\"form-control\" disabled=\"true\"/></td>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t<td>Product Price</td>\r\n");
      out.write("\t\t\t\t\t<td><form:input path=\"pprice\" cssClass=\"form-control\"  disabled=\"true\"/></td>\r\n");
      out.write("\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t<td colspan=2 align=\"center\">\r\n");
      out.write("\t\t\t\t\t<form:hidden path=\"purl\" />\r\n");
      out.write("\t\t\t\t\t<img ng-src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${productImages}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write('/');
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${product.pid}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write(".jpg\" /></td>\r\n");
      out.write("\t\t\t\t</tr>\r\n");
      out.write("\r\n");
      out.write("\t\t\t</table>\r\n");
      out.write("\t\t</form:form>\r\n");
      out.write("\t</div>\r\n");
      out.write("</div>\r\n");
      out.write("</table>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"modal-footer\">\r\n");
      out.write("                <button type=\"button\" class=\"btn btn-default\" data-dismiss=\"modal\">Close</button>\r\n");
      out.write("                <td><a ng-href=\"/yash_webapp_01/pro/displayone/{{x.pid}}\"\r\n");
      out.write("\t\t\t\tclass=\"btn btn-info\" <a  href=\"/yash_webapp_01/cart\">Add to Cart</a>></a></td>\r\n");
      out.write("                \r\n");
      out.write("                            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("</div>\r\n");
      out.write("  \r\n");
      out.write("  <p class=\"text-center text-muted\">\r\n");
      out.write("\r\n");
      out.write("    \r\n");
      out.write("  </p>\r\n");
      out.write("  \r\n");
      out.write("  <p class=\"text-center\">\r\n");
      out.write("\r\n");
      out.write("  </p>\r\n");
      out.write("  \r\n");
      out.write("</div>\r\n");
      out.write("      <script src=\"//assets.codepen.io/assets/common/stopExecutionOnTimeout-53beeb1a007ec32040abaf4c9385ebfc.js\"></script>\r\n");
      out.write("\r\n");
      out.write("    <script src='//ajax.googleapis.com/ajax/libs/angularjs/1.3.2/angular.min.js'></script>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("     <div class=\"popup\">\r\n");
      out.write("     \r\n");
      out.write("      <span class=\"popup-btn-close\">close</span>\r\n");
      out.write("    </div>\r\n");
      out.write("    \r\n");
      out.write("    <script src=\"http://ajax.googleapis.com/ajax/libs/jquery/1.11.1/jquery.min.js\"></script>\r\n");
      out.write("    \r\n");
      out.write("    <script>\r\n");
      out.write("    // Popup Window\r\n");
      out.write("    var scrollTop = '';\r\n");
      out.write("    var newHeight = '100';\r\n");
      out.write("\r\n");
      out.write("    $(window).bind('scroll', function() {\r\n");
      out.write("       scrollTop = $( window ).scrollTop();\r\n");
      out.write("       newHeight = scrollTop + 100;\r\n");
      out.write("    });\r\n");
      out.write("    \r\n");
      out.write("    $('.popup-trigger').click(function(e) {\r\n");
      out.write("       e.stopPropagation();\r\n");
      out.write("     if(jQuery(window).width() < 767) {\r\n");
      out.write("       $(this).after( $( \".popup\" ) );\r\n");
      out.write("       $('.popup').show().addClass('popup-mobile').css('top', 0);\r\n");
      out.write("       $('html, body').animate({\r\n");
      out.write("        scrollTop: $('.popup').offset().top\r\n");
      out.write("      }, 500);   \r\n");
      out.write("     } else {\r\n");
      out.write("       $('.popup').removeClass('popup-mobile').css('top', newHeight).toggle();\r\n");
      out.write("     };\r\n");
      out.write("    });\r\n");
      out.write("    \r\n");
      out.write("    $('html').click(function() {\r\n");
      out.write("     $('.popup').hide();\r\n");
      out.write("    });\r\n");
      out.write("\r\n");
      out.write("    $('.popup-btn-close').click(function(e){\r\n");
      out.write("      $('.popup').hide();\r\n");
      out.write("    });\r\n");
      out.write("\r\n");
      out.write("    $('.popup').click(function(e){\r\n");
      out.write("      e.stopPropagation();\r\n");
      out.write("    });\r\n");
      out.write("    </script>\r\n");
      out.write(" <div class=\"container\">\r\n");
      out.write("  <div class=\"container\">\r\n");
      out.write("    &nbsp;\r\n");
      out.write("  </div>\r\n");
      out.write("   <div class=\"container\">\r\n");
      out.write("    &nbsp;\r\n");
      out.write("  </div>\r\n");
      out.write("   <div class=\"container\">\r\n");
      out.write("    &nbsp;\r\n");
      out.write("  </div>\r\n");
      out.write("   <div class=\"container\">\r\n");
      out.write("    &nbsp;\r\n");
      out.write("  </div>\r\n");
      out.write("   <div class=\"container\">\r\n");
      out.write("    &nbsp;\r\n");
      out.write("  </div>\r\n");
      out.write("   <div class=\"container\">\r\n");
      out.write("    &nbsp;\r\n");
      out.write("  </div>\r\n");
      out.write("   <div class=\"container\">\r\n");
      out.write("    &nbsp;\r\n");
      out.write("  </div>\r\n");
      out.write("   <div class=\"container\">\r\n");
      out.write("    &nbsp;\r\n");
      out.write("  </div>\r\n");
      out.write("   <div class=\"container\">\r\n");
      out.write("    &nbsp;\r\n");
      out.write("  </div>\r\n");
      out.write("   <div class=\"container\">\r\n");
      out.write("    &nbsp;\r\n");
      out.write("  </div>\r\n");
      out.write("   <div class=\"container\">\r\n");
      out.write("    &nbsp;\r\n");
      out.write("  </div>\r\n");
      out.write("    &nbsp;\r\n");
      out.write("  </div>\r\n");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "footer.jsp", out, false);
      out.write("\r\n");
      out.write("  </body>\r\n");
      out.write("  </html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_c_005fset_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:set
    org.apache.taglibs.standard.tag.rt.core.SetTag _jspx_th_c_005fset_005f0 = (org.apache.taglibs.standard.tag.rt.core.SetTag) _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.SetTag.class);
    _jspx_th_c_005fset_005f0.setPageContext(_jspx_page_context);
    _jspx_th_c_005fset_005f0.setParent(null);
    // /WEB-INF/views/viewall.jsp(150,0) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_c_005fset_005f0.setVar("req");
    // /WEB-INF/views/viewall.jsp(150,0) name = value type = javax.el.ValueExpression reqTime = true required = false fragment = false deferredValue = true expectedTypeName = java.lang.Object deferredMethod = false methodSignature = null
    _jspx_th_c_005fset_005f0.setValue(new org.apache.jasper.el.JspValueExpression("/WEB-INF/views/viewall.jsp(150,0) '${pageContext.request.contextPath}'",_jsp_getExpressionFactory().createValueExpression(_jspx_page_context.getELContext(),"${pageContext.request.contextPath}",java.lang.Object.class)).getValue(_jspx_page_context.getELContext()));
    int _jspx_eval_c_005fset_005f0 = _jspx_th_c_005fset_005f0.doStartTag();
    if (_jspx_th_c_005fset_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.reuse(_jspx_th_c_005fset_005f0);
      return true;
    }
    _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.reuse(_jspx_th_c_005fset_005f0);
    return false;
  }
}
