/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.0.35
 * Generated at: 2016-10-22 07:05:52 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class Product_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

final java.lang.String _jspx_method = request.getMethod();
if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
return;
}

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<style>\r\n");
      out.write("  .carousel-inner > .item > img,\r\n");
      out.write("  .carousel-inner > .item > a > img {\r\n");
      out.write("      width: 70%;\r\n");
      out.write("      margin: auto;\r\n");
      out.write("      \r\n");
      out.write("  }\r\n");
      out.write("</style>\r\n");
      out.write("\r\n");
      out.write("<!-- let's add nav css -->\r\n");
      out.write("\r\n");
      out.write("  <link rel=\"stylesheet\" href=\"https://maxcdn.bootstrapcdn.com/bootst\r\n");
      out.write("  rap/3.3.7/css/bootstrap.min.css\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"./resources/my.css\">\r\n");
      out.write("<link href=\"/css/bootstrap.min.css\" rel=\"stylesheet\">\r\n");
      out.write("<link href=\"/css/styles.css\" rel=\"stylesheet\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"css/demo.css\">\r\n");
      out.write("\t<link rel=\"stylesheet\" href=\"css/footer-basic-centered.css\">\r\n");
      out.write("\t<link rel=\"stylesheet\" href=\"./resources/crunchify.css\">\r\n");
      out.write(" <script src=\"https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js\"></script>\r\n");
      out.write("  <script src=\"https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js\"></script>\r\n");
      out.write("  \r\n");
      out.write("\r\n");
      out.write("  \r\n");
      out.write("<!-- Finish adding tags -->\r\n");
      out.write("  \r\n");
      out.write("<title>Happy World</title>\r\n");
      out.write("<style type=\"text/css\">\r\n");
      out.write("body {\r\n");
      out.write("\tbackground-image: url('http://crunchify.com/bg.png');\r\n");
      out.write("}\r\n");
      out.write("#footer{background:#336; padding-top:30px; padding-bottom:30px; text-align:center; border-top:solid 4px #303}\r\n");
      out.write("#footer p{padding:10px; color:#fff}\r\n");
      out.write(".dont-remove{color:#fff !important; text-decoration:none !important; font-weight:700}\r\n");
      out.write(".rights{display:inline-block; border-top:solid 1px rgba(103, 58, 183, 0.3)}\r\n");
      out.write("</style>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("<div class=\"container-fluid\">\r\n");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "header.jsp", out, false);
      out.write("\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("<div class=\"container\">\r\n");
      out.write("  <br>\r\n");
      out.write("  <div id=\"myCarousel\" class=\"carousel slide\" data-ride=\"carousel\">\r\n");
      out.write("    <!-- Indicators -->\r\n");
      out.write("    <ol class=\"carousel-indicators\">\r\n");
      out.write("      <li data-target=\"#myCarousel\" data-slide-to=\"0\" class=\"active\"></li>\r\n");
      out.write("      <li data-target=\"#myCarousel\" data-slide-to=\"1\"></li>\r\n");
      out.write("      <li data-target=\"#myCarousel\" data-slide-to=\"2\"></li>\r\n");
      out.write("      <li data-target=\"#myCarousel\" data-slide-to=\"3\"></li>\r\n");
      out.write("      <li data-target=\"#myCarousel\" data-slide-to=\"4\"></li>\r\n");
      out.write("      <li data-target=\"#myCarousel\" data-slide-to=\"5\"></li>\r\n");
      out.write("      <li data-target=\"#myCarousel\" data-slide-to=\"6\"></li>\r\n");
      out.write("      <li data-target=\"#myCarousel\" data-slide-to=\"7\"></li>\r\n");
      out.write("      \r\n");
      out.write("    </ol>\r\n");
      out.write("    <div class=\"form-group\">\r\n");
      out.write("    &nbsp;\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("  <div class=\"row\">\r\n");
      out.write("            <div class=\"col-lg-12\">\r\n");
      out.write("                <h3 align=\"center\">Check out our Categories</h3>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("        <!-- /.row -->\r\n");
      out.write("\r\n");
      out.write("        <!-- Page Features -->\r\n");
      out.write("        <div class=\"row text-center\">\r\n");
      out.write("\r\n");
      out.write("            <div class=\"col-md-3 col-sm-6 hero-feature\">\r\n");
      out.write("                <div class=\"thumbnail\">\r\n");
      out.write("                    <img src=\"./resources/img/laptop.jpg\"  width=\"500\" height=\"500\">\r\n");
      out.write("                    <div class=\"caption\">\r\n");
      out.write("                        <h3>Laptops</h3>\r\n");
      out.write("                        <p>A grand variety of laptops at each and every price variations for everyone to buy</p>\r\n");
      out.write("                        <p>\r\n");
      out.write("                            <a href=\"#\" class=\"btn btn-primary\">Buy Now!</a> <a href=\"#\" class=\"btn btn-default\">More Info</a>\r\n");
      out.write("                        </p>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("\r\n");
      out.write("            <div class=\"col-md-3 col-sm-6 hero-feature\">\r\n");
      out.write("                <div class=\"thumbnail\">\r\n");
      out.write("                    <img src=\"./resources/img/tv.jpg\"  width=\"250\" height=\"250\">\r\n");
      out.write("                    <div class=\"caption\">\r\n");
      out.write("                        <h3>TV</h3>\r\n");
      out.write("                        <p>A different collection of TV and Hometheatres for the evrey types of people at best price</p> \r\n");
      out.write("                        <p>\r\n");
      out.write("                            <a href=\"#\" class=\"btn btn-primary\">Buy Now!</a> <a href=\"#\" class=\"btn btn-default\">More Info</a>\r\n");
      out.write("                        </p>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("\r\n");
      out.write("            <div class=\"col-md-3 col-sm-6 hero-feature\">\r\n");
      out.write("                <div class=\"thumbnail\">\r\n");
      out.write("                    <img src=\"./resources/img/mobile.jpg\"  width=\"250\" height=\"250\">\r\n");
      out.write("                    <div class=\"caption\">\r\n");
      out.write("                        <h3>Mobiles</h3>\r\n");
      out.write("                        <p>Hot and Cool phones in different styles for the everyone</p>\r\n");
      out.write("                        <p>\r\n");
      out.write("                            <a href=\"#\" class=\"btn btn-primary\">Buy Now!</a> <a href=\"#\" class=\"btn btn-default\">More Info</a>\r\n");
      out.write("                        </p>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("\r\n");
      out.write("            <div class=\"col-md-3 col-sm-6 hero-feature\">\r\n");
      out.write("                <div class=\"thumbnail\">\r\n");
      out.write("                    <img src=\"./resources/img/kitchenappliances.jpg\"  width=\"250\" height=\"250\">\r\n");
      out.write("                    <div class=\"caption\">\r\n");
      out.write("                        <h3>Home Appliance</h3>\r\n");
      out.write("                        <p>A range of home needs in electronics at a single and a super collection</p>\r\n");
      out.write("                        <p>\r\n");
      out.write("                            <a href=\"#\" class=\"btn btn-primary\">Buy Now!</a> <a href=\"#\" class=\"btn btn-default\">More Info</a>\r\n");
      out.write("                        </p>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("\r\n");
      out.write("        </div>\r\n");
      out.write("        <!-- /.row -->\r\n");
      out.write("\r\n");
      out.write("        <hr>\r\n");
      out.write("\r\n");
      out.write("       \r\n");
      out.write("    </div>\r\n");
      out.write("      <div class=\"row\">\r\n");
      out.write("            <div class=\"col-lg-12\">\r\n");
      out.write("                \r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("        <!-- /.row -->\r\n");
      out.write("\r\n");
      out.write("        <!-- Page Features -->\r\n");
      out.write("        <div class=\"row text-center\">\r\n");
      out.write("\r\n");
      out.write("            <div class=\"col-md-3 col-sm-6 hero-feature\">\r\n");
      out.write("                <div class=\"thumbnail\">\r\n");
      out.write("                    <img src=\"./resources/img/computer.jpg\"  width=\"500\" height=\"500\">\r\n");
      out.write("                    <div class=\"caption\">\r\n");
      out.write("                        <h3>Computer</h3>\r\n");
      out.write("                        <p>Special and unique collection of computers and desktop PCs for the younger ones</p>\r\n");
      out.write("                        <p>\r\n");
      out.write("                            <a href=\"#\" class=\"btn btn-primary\">Buy Now!</a> <a href=\"#\" class=\"btn btn-default\">More Info</a>\r\n");
      out.write("                        </p>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("\r\n");
      out.write("            <div class=\"col-md-3 col-sm-6 hero-feature\">\r\n");
      out.write("                <div class=\"thumbnail\">\r\n");
      out.write("                    <img src=\"./resources/img/musicplayer.jpg\"  width=\"250\" height=\"250\">\r\n");
      out.write("                    <div class=\"caption\">\r\n");
      out.write("                        <h3>Music Player</h3>\r\n");
      out.write("                        <p>feel the music around you and in every thing with the high quality music players</p> \r\n");
      out.write("                        <p>\r\n");
      out.write("                            <a href=\"#\" class=\"btn btn-primary\">Buy Now!</a> <a href=\"#\" class=\"btn btn-default\">More Info</a>\r\n");
      out.write("                        </p>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("\r\n");
      out.write("            <div class=\"col-md-3 col-sm-6 hero-feature\">\r\n");
      out.write("                <div class=\"thumbnail\">\r\n");
      out.write("                    <img src=\"./resources/img/refrigerator.jpg\"  width=\"250\" height=\"250\">\r\n");
      out.write("                    <div class=\"caption\">\r\n");
      out.write("                        <h3>Refrigerator</h3>\r\n");
      out.write("                        <p>A great range of smart refrigerators of top brand for your special ones</p>\r\n");
      out.write("                        <p>\r\n");
      out.write("                            <a href=\"#\" class=\"btn btn-primary\">Buy Now!</a> <a href=\"#\" class=\"btn btn-default\">More Info</a>\r\n");
      out.write("                        </p>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("\r\n");
      out.write("            <div class=\"col-md-3 col-sm-6 hero-feature\">\r\n");
      out.write("                <div class=\"thumbnail\">\r\n");
      out.write("                    <img src=\"./resources/img/slider-washingmachines.gif\"  width=\"250\" height=\"250\">\r\n");
      out.write("                    <div class=\"caption\">\r\n");
      out.write("                        <h3>Washing machines</h3>\r\n");
      out.write("                        <p>High quality machines for the love of your clothes</p>\r\n");
      out.write("                        <p>\r\n");
      out.write("                            <a href=\"#\" class=\"btn btn-primary\">Buy Now!</a> <a href=\"#\" class=\"btn btn-default\">More Info</a>\r\n");
      out.write("                        </p>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("\r\n");
      out.write("        </div>\r\n");
      out.write("        <!-- /.row -->\r\n");
      out.write("\r\n");
      out.write("        <hr>\r\n");
      out.write("\r\n");
      out.write("      \r\n");
      out.write("\r\n");
      out.write("    </div>\r\n");
      out.write("              <hr>\r\n");
      out.write("\r\n");
      out.write("        <!-- Footer -->\r\n");
      out.write("        <footer>\r\n");
      out.write("            <div class=\"row\">\r\n");
      out.write("                <div class=\"col-lg-12\">\r\n");
      out.write("                    <p>Copyright &copy; Your Website 2014</p>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </footer>\r\n");
      out.write("\r\n");
      out.write("    \r\n");
      out.write("    <div class=\"container-fluid\">\r\n");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "footer.jsp", out, false);
      out.write("\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
