/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.0.35
 * Generated at: 2016-10-22 08:33:37 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class signin_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

final java.lang.String _jspx_method = request.getMethod();
if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
return;
}

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"en\">\r\n");
      out.write("<head>\r\n");
      out.write("    <meta charset=\"utf-8\">\r\n");
      out.write("    <meta name=\"robots\" content=\"noindex\">\r\n");
      out.write("\r\n");
      out.write("    <title>Custom Login, Registration &amp; Forgot Password - Bootsnipp.com</title>\r\n");
      out.write("        <meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\r\n");
      out.write("    <link href=\"//maxcdn.bootstrapcdn.com/bootstrap/3.3.0/css/bootstrap.min.css\" rel=\"stylesheet\" id=\"bootstrap-css\">\r\n");
      out.write("    <style type=\"text/css\">\r\n");
      out.write("    /*------------------------------------------------------------------\r\n");
      out.write("[Master Stylesheet]\r\n");
      out.write("\r\n");
      out.write("Project    \t: Aether\r\n");
      out.write("Version\t\t: 1.0\r\n");
      out.write("Last change\t: 2015/03/27\r\n");
      out.write("-------------------------------------------------------------------*/\r\n");
      out.write("/*------------------------------------------------------------------\r\n");
      out.write("[Table of contents]\r\n");
      out.write("\r\n");
      out.write("1. General Structure\r\n");
      out.write("2. Anchor Link\r\n");
      out.write("3. Text Outside the Box\r\n");
      out.write("4. Main Form\r\n");
      out.write("5. Login Button\r\n");
      out.write("6. Form Invalid\r\n");
      out.write("7. Form - Main Message\r\n");
      out.write("8. Custom Checkbox & Radio\r\n");
      out.write("9. Misc\r\n");
      out.write("-------------------------------------------------------------------*/\r\n");
      out.write("/*=== 1. General Structure ===*/\r\n");
      out.write("html,\r\n");
      out.write("body {\r\n");
      out.write("  background: #efefef;\r\n");
      out.write("  padding: 10px;\r\n");
      out.write("  font-family: 'Varela Round';\r\n");
      out.write("}\r\n");
      out.write("/*=== 2. Anchor Link ===*/\r\n");
      out.write("a {\r\n");
      out.write("  color: #aaaaaa;\r\n");
      out.write("  transition: all ease-in-out 200ms;\r\n");
      out.write("}\r\n");
      out.write("a:hover {\r\n");
      out.write("  color: #333333;\r\n");
      out.write("  text-decoration: none;\r\n");
      out.write("}\r\n");
      out.write("/*=== 3. Text Outside the Box ===*/\r\n");
      out.write(".etc-login-form {\r\n");
      out.write("  color: #919191;\r\n");
      out.write("  padding: 10px 20px;\r\n");
      out.write("}\r\n");
      out.write(".etc-login-form p {\r\n");
      out.write("  margin-bottom: 5px;\r\n");
      out.write("}\r\n");
      out.write("/*=== 4. Main Form ===*/\r\n");
      out.write(".login-form-1 {\r\n");
      out.write("  max-width: 300px;\r\n");
      out.write("  border-radius: 5px;\r\n");
      out.write("  display: inline-block;\r\n");
      out.write("}\r\n");
      out.write(".main-login-form {\r\n");
      out.write("  position: relative;\r\n");
      out.write("}\r\n");
      out.write(".login-form-1 .form-control {\r\n");
      out.write("  border: 0;\r\n");
      out.write("  box-shadow: 0 0 0;\r\n");
      out.write("  border-radius: 0;\r\n");
      out.write("  background: transparent;\r\n");
      out.write("  color: #555555;\r\n");
      out.write("  padding: 7px 0;\r\n");
      out.write("  font-weight: bold;\r\n");
      out.write("  height:auto;\r\n");
      out.write("}\r\n");
      out.write(".login-form-1 .form-control::-webkit-input-placeholder {\r\n");
      out.write("  color: #999999;\r\n");
      out.write("}\r\n");
      out.write(".login-form-1 .form-control:-moz-placeholder,\r\n");
      out.write(".login-form-1 .form-control::-moz-placeholder,\r\n");
      out.write(".login-form-1 .form-control:-ms-input-placeholder {\r\n");
      out.write("  color: #999999;\r\n");
      out.write("}\r\n");
      out.write(".login-form-1 .form-group {\r\n");
      out.write("  margin-bottom: 0;\r\n");
      out.write("  border-bottom: 2px solid #efefef;\r\n");
      out.write("  padding-right: 20px;\r\n");
      out.write("  position: relative;\r\n");
      out.write("}\r\n");
      out.write(".login-form-1 .form-group:last-child {\r\n");
      out.write("  border-bottom: 0;\r\n");
      out.write("}\r\n");
      out.write(".login-group {\r\n");
      out.write("  background: #ffffff;\r\n");
      out.write("  color: #999999;\r\n");
      out.write("  border-radius: 8px;\r\n");
      out.write("  padding: 10px 20px;\r\n");
      out.write("}\r\n");
      out.write(".login-group-checkbox {\r\n");
      out.write("  padding: 5px 0;\r\n");
      out.write("}\r\n");
      out.write("/*=== 5. Login Button ===*/\r\n");
      out.write(".login-form-1 .login-button {\r\n");
      out.write("  position: absolute;\r\n");
      out.write("  right: -25px;\r\n");
      out.write("  top: 50%;\r\n");
      out.write("  background: #ffffff;\r\n");
      out.write("  color: #999999;\r\n");
      out.write("  padding: 11px 0;\r\n");
      out.write("  width: 50px;\r\n");
      out.write("  height: 50px;\r\n");
      out.write("  margin-top: -25px;\r\n");
      out.write("  border: 5px solid #efefef;\r\n");
      out.write("  border-radius: 50%;\r\n");
      out.write("  transition: all ease-in-out 500ms;\r\n");
      out.write("}\r\n");
      out.write(".login-form-1 .login-button:hover {\r\n");
      out.write("  color: #555555;\r\n");
      out.write("  transform: rotate(450deg);\r\n");
      out.write("}\r\n");
      out.write(".login-form-1 .login-button.clicked {\r\n");
      out.write("  color: #555555;\r\n");
      out.write("}\r\n");
      out.write(".login-form-1 .login-button.clicked:hover {\r\n");
      out.write("  transform: none;\r\n");
      out.write("}\r\n");
      out.write(".login-form-1 .login-button.clicked.success {\r\n");
      out.write("  color: #2ecc71;\r\n");
      out.write("}\r\n");
      out.write(".login-form-1 .login-button.clicked.error {\r\n");
      out.write("  color: #e74c3c;\r\n");
      out.write("}\r\n");
      out.write("/*=== 6. Form Invalid ===*/\r\n");
      out.write("label.form-invalid {\r\n");
      out.write("  position: absolute;\r\n");
      out.write("  top: 0;\r\n");
      out.write("  right: 0;\r\n");
      out.write("  z-index: 5;\r\n");
      out.write("  display: block;\r\n");
      out.write("  margin-top: -25px;\r\n");
      out.write("  padding: 7px 9px;\r\n");
      out.write("  background: #777777;\r\n");
      out.write("  color: #ffffff;\r\n");
      out.write("  border-radius: 5px;\r\n");
      out.write("  font-weight: bold;\r\n");
      out.write("  font-size: 11px;\r\n");
      out.write("}\r\n");
      out.write("label.form-invalid:after {\r\n");
      out.write("  top: 100%;\r\n");
      out.write("  right: 10px;\r\n");
      out.write("  border: solid transparent;\r\n");
      out.write("  content: \" \";\r\n");
      out.write("  height: 0;\r\n");
      out.write("  width: 0;\r\n");
      out.write("  position: absolute;\r\n");
      out.write("  pointer-events: none;\r\n");
      out.write("  border-color: transparent;\r\n");
      out.write("  border-top-color: #777777;\r\n");
      out.write("  border-width: 6px;\r\n");
      out.write("}\r\n");
      out.write("/*=== 7. Form - Main Message ===*/\r\n");
      out.write(".login-form-main-message {\r\n");
      out.write("  background: #ffffff;\r\n");
      out.write("  color: #999999;\r\n");
      out.write("  border-left: 3px solid transparent;\r\n");
      out.write("  border-radius: 3px;\r\n");
      out.write("  margin-bottom: 8px;\r\n");
      out.write("  font-weight: bold;\r\n");
      out.write("  height: 0;\r\n");
      out.write("  padding: 0 20px 0 17px;\r\n");
      out.write("  opacity: 0;\r\n");
      out.write("  transition: all ease-in-out 200ms;\r\n");
      out.write("}\r\n");
      out.write(".login-form-main-message.show {\r\n");
      out.write("  height: auto;\r\n");
      out.write("  opacity: 1;\r\n");
      out.write("  padding: 10px 20px 10px 17px;\r\n");
      out.write("}\r\n");
      out.write(".login-form-main-message.success {\r\n");
      out.write("  border-left-color: #2ecc71;\r\n");
      out.write("}\r\n");
      out.write(".login-form-main-message.error {\r\n");
      out.write("  border-left-color: #e74c3c;\r\n");
      out.write("}\r\n");
      out.write("/*=== 8. Custom Checkbox & Radio ===*/\r\n");
      out.write("/* Base for label styling */\r\n");
      out.write("[type=\"checkbox\"]:not(:checked),\r\n");
      out.write("[type=\"checkbox\"]:checked,\r\n");
      out.write("[type=\"radio\"]:not(:checked),\r\n");
      out.write("[type=\"radio\"]:checked {\r\n");
      out.write("  position: absolute;\r\n");
      out.write("  left: -9999px;\r\n");
      out.write("}\r\n");
      out.write("[type=\"checkbox\"]:not(:checked) + label,\r\n");
      out.write("[type=\"checkbox\"]:checked + label,\r\n");
      out.write("[type=\"radio\"]:not(:checked) + label,\r\n");
      out.write("[type=\"radio\"]:checked + label {\r\n");
      out.write("  position: relative;\r\n");
      out.write("  padding-left: 25px;\r\n");
      out.write("  padding-top: 1px;\r\n");
      out.write("  cursor: pointer;\r\n");
      out.write("}\r\n");
      out.write("/* checkbox aspect */\r\n");
      out.write("[type=\"checkbox\"]:not(:checked) + label:before,\r\n");
      out.write("[type=\"checkbox\"]:checked + label:before,\r\n");
      out.write("[type=\"radio\"]:not(:checked) + label:before,\r\n");
      out.write("[type=\"radio\"]:checked + label:before {\r\n");
      out.write("  content: '';\r\n");
      out.write("  position: absolute;\r\n");
      out.write("  left: 0;\r\n");
      out.write("  top: 2px;\r\n");
      out.write("  width: 17px;\r\n");
      out.write("  height: 17px;\r\n");
      out.write("  border: 0px solid #aaa;\r\n");
      out.write("  background: #f0f0f0;\r\n");
      out.write("  border-radius: 3px;\r\n");
      out.write("  box-shadow: inset 0 1px 3px rgba(0, 0, 0, 0.3);\r\n");
      out.write("}\r\n");
      out.write("/* checked mark aspect */\r\n");
      out.write("[type=\"checkbox\"]:not(:checked) + label:after,\r\n");
      out.write("[type=\"checkbox\"]:checked + label:after,\r\n");
      out.write("[type=\"radio\"]:not(:checked) + label:after,\r\n");
      out.write("[type=\"radio\"]:checked + label:after {\r\n");
      out.write("  position: absolute;\r\n");
      out.write("  color: #555555;\r\n");
      out.write("  transition: all .2s;\r\n");
      out.write("}\r\n");
      out.write("/* checked mark aspect changes */\r\n");
      out.write("[type=\"checkbox\"]:not(:checked) + label:after,\r\n");
      out.write("[type=\"radio\"]:not(:checked) + label:after {\r\n");
      out.write("  opacity: 0;\r\n");
      out.write("  transform: scale(0);\r\n");
      out.write("}\r\n");
      out.write("[type=\"checkbox\"]:checked + label:after,\r\n");
      out.write("[type=\"radio\"]:checked + label:after {\r\n");
      out.write("  opacity: 1;\r\n");
      out.write("  transform: scale(1);\r\n");
      out.write("}\r\n");
      out.write("/* disabled checkbox */\r\n");
      out.write("[type=\"checkbox\"]:disabled:not(:checked) + label:before,\r\n");
      out.write("[type=\"checkbox\"]:disabled:checked + label:before,\r\n");
      out.write("[type=\"radio\"]:disabled:not(:checked) + label:before,\r\n");
      out.write("[type=\"radio\"]:disabled:checked + label:before {\r\n");
      out.write("  box-shadow: none;\r\n");
      out.write("  border-color: #8c8c8c;\r\n");
      out.write("  background-color: #878787;\r\n");
      out.write("}\r\n");
      out.write("[type=\"checkbox\"]:disabled:checked + label:after,\r\n");
      out.write("[type=\"radio\"]:disabled:checked + label:after {\r\n");
      out.write("  color: #555555;\r\n");
      out.write("}\r\n");
      out.write("[type=\"checkbox\"]:disabled + label,\r\n");
      out.write("[type=\"radio\"]:disabled + label {\r\n");
      out.write("  color: #8c8c8c;\r\n");
      out.write("}\r\n");
      out.write("/* accessibility */\r\n");
      out.write("[type=\"checkbox\"]:checked:focus + label:before,\r\n");
      out.write("[type=\"checkbox\"]:not(:checked):focus + label:before,\r\n");
      out.write("[type=\"checkbox\"]:checked:focus + label:before,\r\n");
      out.write("[type=\"checkbox\"]:not(:checked):focus + label:before {\r\n");
      out.write("  border: 1px dotted #f6f6f6;\r\n");
      out.write("}\r\n");
      out.write("/* hover style just for information */\r\n");
      out.write("label:hover:before {\r\n");
      out.write("  border: 1px solid #f6f6f6 !important;\r\n");
      out.write("}\r\n");
      out.write("/*=== Customization ===*/\r\n");
      out.write("/* radio aspect */\r\n");
      out.write("[type=\"checkbox\"]:not(:checked) + label:before,\r\n");
      out.write("[type=\"checkbox\"]:checked + label:before {\r\n");
      out.write("  border-radius: 3px;\r\n");
      out.write("}\r\n");
      out.write("[type=\"radio\"]:not(:checked) + label:before,\r\n");
      out.write("[type=\"radio\"]:checked + label:before {\r\n");
      out.write("  border-radius: 35px;\r\n");
      out.write("}\r\n");
      out.write("/* selected mark aspect */\r\n");
      out.write("[type=\"checkbox\"]:not(:checked) + label:after,\r\n");
      out.write("[type=\"checkbox\"]:checked + label:after {\r\n");
      out.write("  content: 'â';\r\n");
      out.write("  top: 0;\r\n");
      out.write("  left: 2px;\r\n");
      out.write("  font-size: 14px;\r\n");
      out.write("}\r\n");
      out.write("[type=\"radio\"]:not(:checked) + label:after,\r\n");
      out.write("[type=\"radio\"]:checked + label:after {\r\n");
      out.write("  content: '\\2022';\r\n");
      out.write("  top: 0;\r\n");
      out.write("  left: 3px;\r\n");
      out.write("  font-size: 30px;\r\n");
      out.write("  line-height: 25px;\r\n");
      out.write("}\r\n");
      out.write("/*=== 9. Misc ===*/\r\n");
      out.write(".logo {\r\n");
      out.write("  padding: 15px 0;\r\n");
      out.write("  font-size: 25px;\r\n");
      out.write("  color: #aaaaaa;\r\n");
      out.write("  font-weight: bold;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("    </style>\r\n");
      out.write("    <script src=\"//code.jquery.com/jquery-1.10.2.min.js\"></script>\r\n");
      out.write("    <script src=\"//maxcdn.bootstrapcdn.com/bootstrap/3.3.0/js/bootstrap.min.js\"></script>\r\n");
      out.write("    <script type=\"text/javascript\">\r\n");
      out.write("        window.alert = function(){};\r\n");
      out.write("        var defaultCSS = document.getElementById('bootstrap-css');\r\n");
      out.write("        function changeCSS(css){\r\n");
      out.write("            if(css) $('head > link').filter(':first').replaceWith('<link rel=\"stylesheet\" href=\"'+ css +'\" type=\"text/css\" />'); \r\n");
      out.write("            else $('head > link').filter(':first').replaceWith(defaultCSS); \r\n");
      out.write("        }\r\n");
      out.write("        $( document ).ready(function() {\r\n");
      out.write("          var iframe_height = parseInt($('html').height()); \r\n");
      out.write("          window.parent.postMessage( iframe_height, 'http://bootsnipp.com');\r\n");
      out.write("        });\r\n");
      out.write("    </script>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("<div class=\"container-fluid\">\r\n");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "header.jsp", out, false);
      out.write("\r\n");
      out.write("</div>\r\n");
      out.write("\t<!-- All the files that are required -->\r\n");
      out.write("<link rel=\"stylesheet\" href=\"//maxcdn.bootstrapcdn.com/font-awesome/4.3.0/css/font-awesome.min.css\">\r\n");
      out.write("<link href='http://fonts.googleapis.com/css?family=Varela+Round' rel='stylesheet' type='text/css'>\r\n");
      out.write("<script src=\"https://cdnjs.cloudflare.com/ajax/libs/jquery-validate/1.13.1/jquery.validate.min.js\"></script>\r\n");
      out.write("<meta name=\"viewport\" content=\"width=device-width, initial-scale=1, maximum-scale=1\" />\r\n");
      out.write("\r\n");
      out.write("<!-- Where all the magic happens -->\r\n");
      out.write("<!-- LOGIN FORM -->\r\n");
      out.write("<div class=\"text-center\" style=\"padding:50px 0\">\r\n");
      out.write("\t<div class=\"logo\">login</div>\r\n");
      out.write("\t<!-- Main Form -->\r\n");
      out.write("\t<div class=\"login-form-1\">\r\n");
      out.write("\t\t<form id=\"login-form\" class=\"text-left\">\r\n");
      out.write("\t\t\t<div class=\"login-form-main-message\"></div>\r\n");
      out.write("\t\t\t<div class=\"main-login-form\">\r\n");
      out.write("\t\t\t\t<div class=\"login-group\">\r\n");
      out.write("\t\t\t\t\t<div class=\"form-group\">\r\n");
      out.write("\t\t\t\t\t\t<label for=\"lg_username\" class=\"sr-only\">Username</label>\r\n");
      out.write("\t\t\t\t\t\t<input type=\"text\" class=\"form-control\" id=\"lg_username\" name=\"lg_username\" placeholder=\"username\">\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<div class=\"form-group\">\r\n");
      out.write("\t\t\t\t\t\t<label for=\"lg_password\" class=\"sr-only\">Password</label>\r\n");
      out.write("\t\t\t\t\t\t<input type=\"password\" class=\"form-control\" id=\"lg_password\" name=\"lg_password\" placeholder=\"password\">\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<div class=\"form-group login-group-checkbox\">\r\n");
      out.write("\t\t\t\t\t\t<input type=\"checkbox\" id=\"lg_remember\" name=\"lg_remember\">\r\n");
      out.write("\t\t\t\t\t\t<label for=\"lg_remember\">remember</label>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<button type=\"submit\" class=\"login-button\"><i class=\"fa fa-chevron-right\"></i></button>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<div class=\"etc-login-form\">\r\n");
      out.write("\t\t\t\t<p>forgot your password? <a href=\"#\">click here</a></p>\r\n");
      out.write("\t\t\t\t<p>new user? <a href=\"#\">create new account</a></p>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</form>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<!-- end:Main Form -->\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("<!-- REGISTRATION FORM -->\r\n");
      out.write("<div class=\"text-center\" style=\"padding:50px 0\">\r\n");
      out.write("\t<div class=\"logo\">register</div>\r\n");
      out.write("\t<!-- Main Form -->\r\n");
      out.write("\t<div class=\"login-form-1\">\r\n");
      out.write("\t\t<form id=\"register-form\" class=\"text-left\">\r\n");
      out.write("\t\t\t<div class=\"login-form-main-message\"></div>\r\n");
      out.write("\t\t\t<div class=\"main-login-form\">\r\n");
      out.write("\t\t\t\t<div class=\"login-group\">\r\n");
      out.write("\t\t\t\t\t<div class=\"form-group\">\r\n");
      out.write("\t\t\t\t\t\t<label for=\"reg_username\" class=\"sr-only\">Email address</label>\r\n");
      out.write("\t\t\t\t\t\t<input type=\"text\" class=\"form-control\" id=\"reg_username\" name=\"reg_username\" placeholder=\"username\">\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<div class=\"form-group\">\r\n");
      out.write("\t\t\t\t\t\t<label for=\"reg_password\" class=\"sr-only\">Password</label>\r\n");
      out.write("\t\t\t\t\t\t<input type=\"password\" class=\"form-control\" id=\"reg_password\" name=\"reg_password\" placeholder=\"password\">\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<div class=\"form-group\">\r\n");
      out.write("\t\t\t\t\t\t<label for=\"reg_password_confirm\" class=\"sr-only\">Password Confirm</label>\r\n");
      out.write("\t\t\t\t\t\t<input type=\"password\" class=\"form-control\" id=\"reg_password_confirm\" name=\"reg_password_confirm\" placeholder=\"confirm password\">\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t<div class=\"form-group\">\r\n");
      out.write("\t\t\t\t\t\t<label for=\"reg_email\" class=\"sr-only\">Email</label>\r\n");
      out.write("\t\t\t\t\t\t<input type=\"text\" class=\"form-control\" id=\"reg_email\" name=\"reg_email\" placeholder=\"email\">\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<div class=\"form-group\">\r\n");
      out.write("\t\t\t\t\t\t<label for=\"reg_fullname\" class=\"sr-only\">Full Name</label>\r\n");
      out.write("\t\t\t\t\t\t<input type=\"text\" class=\"form-control\" id=\"reg_fullname\" name=\"reg_fullname\" placeholder=\"full name\">\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t<div class=\"form-group login-group-checkbox\">\r\n");
      out.write("\t\t\t\t\t\t<input type=\"radio\" class=\"\" name=\"reg_gender\" id=\"male\" placeholder=\"username\">\r\n");
      out.write("\t\t\t\t\t\t<label for=\"male\">male</label>\r\n");
      out.write("\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t<input type=\"radio\" class=\"\" name=\"reg_gender\" id=\"female\" placeholder=\"username\">\r\n");
      out.write("\t\t\t\t\t\t<label for=\"female\">female</label>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t<div class=\"form-group login-group-checkbox\">\r\n");
      out.write("\t\t\t\t\t\t<input type=\"checkbox\" class=\"\" id=\"reg_agree\" name=\"reg_agree\">\r\n");
      out.write("\t\t\t\t\t\t<label for=\"reg_agree\">i agree with <a href=\"#\">terms</a></label>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<button type=\"submit\" class=\"login-button\"><i class=\"fa fa-chevron-right\"></i></button>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<div class=\"etc-login-form\">\r\n");
      out.write("\t\t\t\t<p>already have an account? <a href=\"#\">login here</a></p>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</form>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<!-- end:Main Form -->\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("<!-- FORGOT PASSWORD FORM -->\r\n");
      out.write("<div class=\"text-center\" style=\"padding:50px 0\">\r\n");
      out.write("\t<div class=\"logo\">forgot password</div>\r\n");
      out.write("\t<!-- Main Form -->\r\n");
      out.write("\t<div class=\"login-form-1\">\r\n");
      out.write("\t\t<form id=\"forgot-password-form\" class=\"text-left\">\r\n");
      out.write("\t\t\t<div class=\"etc-login-form\">\r\n");
      out.write("\t\t\t\t<p>When you fill in your registered email address, you will be sent instructions on how to reset your password.</p>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<div class=\"login-form-main-message\"></div>\r\n");
      out.write("\t\t\t<div class=\"main-login-form\">\r\n");
      out.write("\t\t\t\t<div class=\"login-group\">\r\n");
      out.write("\t\t\t\t\t<div class=\"form-group\">\r\n");
      out.write("\t\t\t\t\t\t<label for=\"fp_email\" class=\"sr-only\">Email address</label>\r\n");
      out.write("\t\t\t\t\t\t<input type=\"text\" class=\"form-control\" id=\"fp_email\" name=\"fp_email\" placeholder=\"email address\">\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<button type=\"submit\" class=\"login-button\"><i class=\"fa fa-chevron-right\"></i></button>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<div class=\"etc-login-form\">\r\n");
      out.write("\t\t\t\t<p>already have an account? <a href=\"#\">login here</a></p>\r\n");
      out.write("\t\t\t\t<p>new user? <a href=\"#\">create new account</a></p>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</form>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<!-- end:Main Form -->\r\n");
      out.write("</div>\r\n");
      out.write("\t<script type=\"text/javascript\">\r\n");
      out.write("\t(function($) {\r\n");
      out.write("    \"use strict\";\r\n");
      out.write("\t\r\n");
      out.write("\t// Options for Message\r\n");
      out.write("\t//----------------------------------------------\r\n");
      out.write("  var options = {\r\n");
      out.write("\t  'btn-loading': '<i class=\"fa fa-spinner fa-pulse\"></i>',\r\n");
      out.write("\t  'btn-success': '<i class=\"fa fa-check\"></i>',\r\n");
      out.write("\t  'btn-error': '<i class=\"fa fa-remove\"></i>',\r\n");
      out.write("\t  'msg-success': 'All Good! Redirecting...',\r\n");
      out.write("\t  'msg-error': 'Wrong login credentials!',\r\n");
      out.write("\t  'useAJAX': true,\r\n");
      out.write("  };\r\n");
      out.write("\r\n");
      out.write("\t// Login Form\r\n");
      out.write("\t//----------------------------------------------\r\n");
      out.write("\t// Validation\r\n");
      out.write("  $(\"#login-form\").validate({\r\n");
      out.write("  \trules: {\r\n");
      out.write("      lg_username: \"required\",\r\n");
      out.write("  \t  lg_password: \"required\",\r\n");
      out.write("    },\r\n");
      out.write("  \terrorClass: \"form-invalid\"\r\n");
      out.write("  });\r\n");
      out.write("  \r\n");
      out.write("\t// Form Submission\r\n");
      out.write("  $(\"#login-form\").submit(function() {\r\n");
      out.write("  \tremove_loading($(this));\r\n");
      out.write("\t\t\r\n");
      out.write("\t\tif(options['useAJAX'] == true)\r\n");
      out.write("\t\t{\r\n");
      out.write("\t\t\t// Dummy AJAX request (Replace this with your AJAX code)\r\n");
      out.write("\t\t  // If you don't want to use AJAX, remove this\r\n");
      out.write("  \t  dummy_submit_form($(this));\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t  // Cancel the normal submission.\r\n");
      out.write("\t\t  // If you don't want to use AJAX, remove this\r\n");
      out.write("  \t  return false;\r\n");
      out.write("\t\t}\r\n");
      out.write("  });\r\n");
      out.write("\t\r\n");
      out.write("\t// Register Form\r\n");
      out.write("\t//----------------------------------------------\r\n");
      out.write("\t// Validation\r\n");
      out.write("  $(\"#register-form\").validate({\r\n");
      out.write("  \trules: {\r\n");
      out.write("      reg_username: \"required\",\r\n");
      out.write("  \t  reg_password: {\r\n");
      out.write("  \t\t\trequired: true,\r\n");
      out.write("  \t\t\tminlength: 5\r\n");
      out.write("  \t\t},\r\n");
      out.write("   \t\treg_password_confirm: {\r\n");
      out.write("  \t\t\trequired: true,\r\n");
      out.write("  \t\t\tminlength: 5,\r\n");
      out.write("  \t\t\tequalTo: \"#register-form [name=reg_password]\"\r\n");
      out.write("  \t\t},\r\n");
      out.write("  \t\treg_email: {\r\n");
      out.write("  \t    required: true,\r\n");
      out.write("  \t\t\temail: true\r\n");
      out.write("  \t\t},\r\n");
      out.write("  \t\treg_agree: \"required\",\r\n");
      out.write("    },\r\n");
      out.write("\t  errorClass: \"form-invalid\",\r\n");
      out.write("\t  errorPlacement: function( label, element ) {\r\n");
      out.write("\t    if( element.attr( \"type\" ) === \"checkbox\" || element.attr( \"type\" ) === \"radio\" ) {\r\n");
      out.write("    \t\telement.parent().append( label ); // this would append the label after all your checkboxes/labels (so the error-label will be the last element in <div class=\"controls\"> )\r\n");
      out.write("\t    }\r\n");
      out.write("\t\t\telse {\r\n");
      out.write("  \t  \tlabel.insertAfter( element ); // standard behaviour\r\n");
      out.write("  \t  }\r\n");
      out.write("    }\r\n");
      out.write("  });\r\n");
      out.write("\r\n");
      out.write("  // Form Submission\r\n");
      out.write("  $(\"#register-form\").submit(function() {\r\n");
      out.write("  \tremove_loading($(this));\r\n");
      out.write("\t\t\r\n");
      out.write("\t\tif(options['useAJAX'] == true)\r\n");
      out.write("\t\t{\r\n");
      out.write("\t\t\t// Dummy AJAX request (Replace this with your AJAX code)\r\n");
      out.write("\t\t  // If you don't want to use AJAX, remove this\r\n");
      out.write("  \t  dummy_submit_form($(this));\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t  // Cancel the normal submission.\r\n");
      out.write("\t\t  // If you don't want to use AJAX, remove this\r\n");
      out.write("  \t  return false;\r\n");
      out.write("\t\t}\r\n");
      out.write("  });\r\n");
      out.write("\r\n");
      out.write("\t// Forgot Password Form\r\n");
      out.write("\t//----------------------------------------------\r\n");
      out.write("\t// Validation\r\n");
      out.write("  $(\"#forgot-password-form\").validate({\r\n");
      out.write("  \trules: {\r\n");
      out.write("      fp_email: \"required\",\r\n");
      out.write("    },\r\n");
      out.write("  \terrorClass: \"form-invalid\"\r\n");
      out.write("  });\r\n");
      out.write("  \r\n");
      out.write("\t// Form Submission\r\n");
      out.write("  $(\"#forgot-password-form\").submit(function() {\r\n");
      out.write("  \tremove_loading($(this));\r\n");
      out.write("\t\t\r\n");
      out.write("\t\tif(options['useAJAX'] == true)\r\n");
      out.write("\t\t{\r\n");
      out.write("\t\t\t// Dummy AJAX request (Replace this with your AJAX code)\r\n");
      out.write("\t\t  // If you don't want to use AJAX, remove this\r\n");
      out.write("  \t  dummy_submit_form($(this));\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t  // Cancel the normal submission.\r\n");
      out.write("\t\t  // If you don't want to use AJAX, remove this\r\n");
      out.write("  \t  return false;\r\n");
      out.write("\t\t}\r\n");
      out.write("  });\r\n");
      out.write("\r\n");
      out.write("\t// Loading\r\n");
      out.write("\t//----------------------------------------------\r\n");
      out.write("  function remove_loading($form)\r\n");
      out.write("  {\r\n");
      out.write("  \t$form.find('[type=submit]').removeClass('error success');\r\n");
      out.write("  \t$form.find('.login-form-main-message').removeClass('show error success').html('');\r\n");
      out.write("  }\r\n");
      out.write("\r\n");
      out.write("  function form_loading($form)\r\n");
      out.write("  {\r\n");
      out.write("    $form.find('[type=submit]').addClass('clicked').html(options['btn-loading']);\r\n");
      out.write("  }\r\n");
      out.write("  \r\n");
      out.write("  function form_success($form)\r\n");
      out.write("  {\r\n");
      out.write("\t  $form.find('[type=submit]').addClass('success').html(options['btn-success']);\r\n");
      out.write("\t  $form.find('.login-form-main-message').addClass('show success').html(options['msg-success']);\r\n");
      out.write("  }\r\n");
      out.write("\r\n");
      out.write("  function form_failed($form)\r\n");
      out.write("  {\r\n");
      out.write("  \t$form.find('[type=submit]').addClass('error').html(options['btn-error']);\r\n");
      out.write("  \t$form.find('.login-form-main-message').addClass('show error').html(options['msg-error']);\r\n");
      out.write("  }\r\n");
      out.write("\r\n");
      out.write("\t// Dummy Submit Form (Remove this)\r\n");
      out.write("\t//----------------------------------------------\r\n");
      out.write("\t// This is just a dummy form submission. You should use your AJAX function or remove this function if you are not using AJAX.\r\n");
      out.write("  function dummy_submit_form($form)\r\n");
      out.write("  {\r\n");
      out.write("  \tif($form.valid())\r\n");
      out.write("  \t{\r\n");
      out.write("  \t\tform_loading($form);\r\n");
      out.write("  \t\t\r\n");
      out.write("  \t\tsetTimeout(function() {\r\n");
      out.write("  \t\t\tform_success($form);\r\n");
      out.write("  \t\t}, 2000);\r\n");
      out.write("  \t}\r\n");
      out.write("  }\r\n");
      out.write("\t\r\n");
      out.write("})(jQuery);\r\n");
      out.write("\t</script>\r\n");
      out.write("</body>\r\n");
      out.write("</html>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
